### PR TITLE
Trivial fixes

### PR DESCRIPTION
**Pull request by g0hl1n**
Some trivial fixes

### CODE REVIEW

**Comment by smackysnacks** [comment]
Thanks again for the contributions @g0hl1n. I had a question about the method used here to suppress the unused variable warnings. What do you think about instead block commenting the unused names instead?

For example
```c++
 PAM_EXTERN int pam_sm_authenticate(pam_handle_t* pamh,
                                    int /* flags */,
                                    int argc,
                                    const char** argv)
```

I believe this should work with all major compilers and it avoids introducing a macro. Let me know your thoughts.

**Comment by g0hl1n** [comment]
That is a solution too, of course.

I suggested the GCC macro simply because that's the way I'm doing it mostly.

Another possibility would be to disable the `unused-variable` warning in the gcc commandline or casting the parameters to void `(void)param1;` at the beginning of the function.

In the end it is IMHO up to you.. how you like it better ;-)

**Comment by smackysnacks** [comment]
I'm gonna say let's go with /* */ on unused variable names. This way we can target other compilers besides gcc. Could you make this change and then I'll merge in your commits?

**Comment by g0hl1n** [comment]
Ok. I've just updated this PR.

**Pull request merged**
